# Generated by Django 5.1.6 on 2025-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_auclisting_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auclisting',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.comment'),
        ),
    ]
