# Generated by Django 5.1.6 on 2025-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auclisting_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auclisting',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
