# Generated by Django 5.1.6 on 2025-05-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auclisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auclisting',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
