# Generated by Django 5.1.6 on 2025-05-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auclisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auclisting',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
