# Generated by Django 5.1.6 on 2025-05-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auclisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auclisting',
            name='startbid',
            field=models.FloatField(),
        ),
    ]
