# Generated by Django 5.1.6 on 2025-05-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auclisting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('listings', models.ManyToManyField(blank=True, related_name='categories', to='auctions.auclisting')),
            ],
        ),
    ]
